language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hgcook/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hgcook/docker-react npm run test